const p = require('path')
const fs = require('fs')

const DIRNAME = 'autogenerated'
const TEST_DIR = p.join(__dirname, DIRNAME)

const tests = fs.readdirSync(TEST_DIR)
for (const test of tests) {
  const module = require(p.join(__dirname, DIRNAME, test))
  if (module.runTests) module.runTests()
}
