const p = require('path')
const fs = require('fs')

const DIRNAME = 'autogenerated'
const TEST_DIR = p.join(__dirname, DIRNAME)

const tests = fs.readdirSync(TEST_DIR)
for (const test of tests) {
  require(p.join(__dirname, DIRNAME, test))
}
