const p = require('path')
const fs = require('fs')

const DIRNAME = 'autogenerated'
const TEST_DIR = p.join(__dirname, DIRNAME)
const FIXED_DIR = p.join(TEST_DIR, 'fixed')
const FAILING_DIR = p.join(TEST_DIR, 'failing')

const argv = require('minimist')(process.argv.slice(2), {
  boolean: ['regression', 'failing']
})
const all = !argv.regression && !argv.failing

var tests = []
if (argv.regression || all) tests.push(...fs.readdirSync(FIXED_DIR).map(n => p.join(FIXED_DIR, n)))
if (argv.failing || all) tests.push(...fs.readdirSync(FAILING_DIR).map(n => p.join(FAILING_DIR, n)))

for (const test of tests) {
  if (test.endsWith('.js')) {
    const module = require(test)
    if (module.runTests) module.runTests()
  }
}
