const test = require('tape')
const Trie = require('../trie')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.symlink('bb', 'bdb')
  await trie.symlink('c', 'dcb')
  await trie.put('b', 'cuhtpmnbbj')
  await trie.put('c', 'ybtvzckxov')
  await trie.symlink('cbcd/bb', 'bb')

  // Should return bdb -> null
  // Actually returns bdb -> bb
  const node = await trie.get('bdb')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, null)
  t.end()
})
