const test = require('tape')
const Trie = require('../../../trie')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.symlink('b/b/../cbc/..', 'c')
  await trie.put('cdd', 'imsoxtsmcg')
  await trie.put('c/b', 'iitytuqocl')

  // Should return b/b -> iitytuqocl
  // Actually returns b/b -> iitytuqocl
  const node = await trie.get('b/b')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, 'iitytuqocl')
  t.end()
})
