const test = require('tape')
const Trie = require('../../..')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.symlink('c', 'cd')
  await trie.symlink('/db/b/b/bd', 'd/d/d/d/d')
  await trie.symlink('/b', 'c/d/d')
  await trie.rename('cd/b', 'db')
  await trie.put('cd/b/bc/d', 'gxnkiwzusv')

  // Should return null -> null
  // Actually returns db/bc/d -> gxnkiwzusv
  const node = await trie.get('db/bc/d')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, null)
  t.end()
})
