const test = require('tape')
const Trie = require('../../..')

test('failing autogenerated test case', async t => {
  const trie = new Trie()
  
  await trie.put('b/b/c/b', 'zuegeyixkp')
  await trie.rename('bc', 'd')
  await trie.put('c', 'zbfqbxfoqp')
  await trie.put('bb/db', 'djbmzjqeqv')
  await trie.put('cd/bb', 'fbpnwxkldh')
  await trie.put('db', 'zmbcolhniv')
  await trie.put('c', 'hrzipywzry')
  await trie.symlink('/cb', 'c')
  await trie.put('c', 'bhjwqftbew')
  
  // Should return null -> null
  // Actually returns cb -> bhjwqftbew
  const node = await trie.get('cb')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, null)
  t.end() 
})
