const test = require('tape')
const Trie = require('../../..')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.put('d', 'hoidqkrqku')
  await trie.rename('d', 'c/bb/d')

  // Should return c/bb/d -> hoidqkrqku
  // Actually returns null -> null
  const node = await trie.get('c/bb/d')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, 'hoidqkrqku')
  t.end()
})
