const test = require('tape')
const Trie = require('../../..')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.symlink('/bb/b/bb', 'b')
  await trie.symlink('/b/b/b/db', 'bb')
  await trie.put('bd/b/b', 'kzklwwfsep')
  await trie.symlink('/c/bd', 'bb/c')

  // Should return bd/b/b -> kzklwwfsep
  // Actually returns null -> null
  const node = await trie.get('bd/b/b')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, 'kzklwwfsep')
  t.end()
})
