const test = require('tape')
const Trie = require('../../../trie')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.put('b/cb/c/d', 'ctplsgkmlb')
  await trie.rename('d/d', 'b')
  await trie.put('b', 'hzhejwvzru')

  // Should return b -> hzhejwvzru
  // Actually returns null -> null
  const node = await trie.get('b')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, 'hzhejwvzru')
  t.end()
})
