const test = require('tape')
const Trie = require('../../..')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.symlink('/b/cc/cb', 'b/c/b')
  await trie.put('d', 'wltrlgrwbd')
  await trie.symlink('bc/bb/cb/../b', 'c/b')
  await trie.put('bc/b/c/d/b', 'ldustbwtqq')
  await trie.symlink('bb/bc/b/b/b', 'b/db/b/d/b')
  await trie.symlink('/cc/bd', 'b/d')
  await trie.put('c/b', 'bwgmogbcnb')
  await trie.rename('d', 'b/b/bd')

  // Should return null -> null
  // Actually returns b -> wltrlgrwbd
  const node = await trie.get('b')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, null)
  t.end()
})
