const test = require('tape')         
const Trie = require('../../..') 
             
test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.symlink('../b', 'c')
  await trie.put('bbc', 'tqhebxznto')
  await trie.put('c', 'bgywbofwbw')
                                                                                
  // Should return null -> null
  // Actually returns b/c -> bgywbofwbw
  const node = await trie.get('b/c')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, null)                                                                              
  t.end()
})                                                                                   
