const test = require('tape')
const Trie = require('../../..')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.rename('d/d', 'b')
  await trie.put('db/b/c/d/b', 'xbhscqvbmf')
  await trie.put('b', 'hzhejwvzru')

  // Should return db/b/c/d/b -> xbhscqvbmf
  // Actually returns null -> null
  const node = await trie.get('db/b/c/d/b')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, 'xbhscqvbmf')
  t.end()
})
