const test = require('tape')
const Trie = require('../../..')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.put('b', 'ysidkrktwe')
  await trie.symlink('/b', 'cc')
  await trie.rename('d/b', 'cc')

  // Should return b -> ysidkrktwe
  // Actually returns null -> null
  const node = await trie.get('b')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, 'ysidkrktwe')
  t.end()
})
