const test = require('tape')
const Trie = require('../../..')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.symlink('cb', 'b')
  await trie.symlink('b/b/b', 'cb')
  await trie.put('b/bd/d', 'wrojcmtmep')

  // Should return null -> null
  // Actually returns cb/bd/d -> wrojcmtmep
  const node = await trie.get('cb/bd/d')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, null)
  t.end()
})
