const test = require('tape')
const Trie = require('../../..')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.put('bb', 'wspwzzthod')
  await trie.rename('bb', 'bb/c')
  await trie.put('bb/c/c/d/b', 'qkbufukrft')

  // Should return bb/c -> wspwzzthod
  // Actually returns null -> null
  const node = await trie.get('bb/c')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, 'wspwzzthod')
  t.end()
})
