const test = require('tape')
const Trie = require('../../..')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.put('b/b/d/bc', 'hunvdbfuzs')
  await trie.rename('b', 'b/b/bd/b')
  await trie.rename('b', 'c/bd')

  // Should return c/bd/b/bd/b/b/d/bc -> hunvdbfuzs
  // Actually returns null -> null
  const node = await trie.get('c/bd/b/bd/b/b/d/bc')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, 'hunvdbfuzs')
  t.end()
})
