const test = require('tape')
const Trie = require('../../../trie')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.put('bb', 'qqnclzydkw')
  await trie.rename('d', 'c')
  await trie.put('b', 'jdfrslbpyq')
  await trie.put('dc/bb/b', 'oytwkivcfh')
  await trie.put('dc', 'jogpibdque')

  // Should return b -> jdfrslbpyq
  // Actually returns null -> null
  const node = await trie.get('b')

  const value = (node && node.value) ? node.value.value : null
  t.same(value, 'jdfrslbpyq')
  t.end()
})
