const test = require('tape')        
const Trie = require('../../..')         
             
test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.put('cbd', 'oeddhhjclw')
  await trie.symlink('/bdbb/c', 'b')
  await trie.put('bbcc/c', 'dxbknodwqm')
                                                                                
  // Should return bbcc/c -> dxbknodwqm
  // Actually returns null -> null
  const node = await trie.get('bbcc/c')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, 'dxbknodwqm')
  t.end()
})
