const test = require('tape')
const Trie = require('../../../trie')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.symlink('c/b/d/b', 'b')
  await trie.put('b/b/c/b', 'hjogmdtqsl')
  await trie.put('b/b/bd/b', 'vshincsfnf')
  await trie.symlink('/bc/b', 'b/c/d/d')

  // Should return c/b/d/b/b/bd/b -> vshincsfnf
  // Actually returns null -> null
  const node = await trie.get('c/b/d/b/b/bd/b')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, 'vshincsfnf')
  t.end()
})
