const test = require('tape')
const Trie = require('../../..')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.put('bbc', 'yuvuxcvbbl')
  await trie.put('b', 'zbdtdxumdz')
  await trie.put('c/b', 'ujkqbziqtn')
  await trie.symlink('c', 'bd')
  await trie.symlink('cd/b', 'b/cbc')

  // Should return bd/b -> ujkqbziqtn
  // Actually returns null -> null
  const node = await trie.get('bd/b')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, 'ujkqbziqtn')
  t.end()
})
