const test = require('tape')
const Trie = require('../../trie')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.put('db/c/d/b', 'qyxhfxkomb')
  await trie.rename('b/c/c', 'b/b/c/b')
  await trie.rename('d', 'c/d')

  // Should return null -> null
  // Actually returns c/db/c/d/b -> qyxhfxkomb
  const node = await trie.get('c/db/c/d/b')

  const value = (node && node.value) ? node.value.value : null
  t.same(value, null)
  t.end()
})

