const test = require('tape')
const Trie = require('../../trie')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.symlink('bd/../d/../../bbb', 'b')
  await trie.symlink('/b', 'db')
  await trie.put('bbb/d', 'tjjseufczl')

  // Should return db/d/d -> null
  // Actually returns db/d/d -> null
  const node = await trie.get('db/d/d')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, null)
  t.end()
})
