const test = require('tape')
const Trie = require('../../trie')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.symlink('b/bd/..', 'cd/b/bb') // .. 
  await trie.symlink('/c/cc/bd/d', 'b/d') // /c/cc/bd/d/(db/b/b)/bc
  await trie.symlink('bb', 'bb/bb/b/bd') // ..
  await trie.symlink('d/db', 'b/cd') // b/d/(db/b/b)/bc
  await trie.put('b/cd/b/b/bc', 'xsujbnxtpq')

  // Should return c/cc/bd/d/bc -> null
  // Actually returns c/cc/bd/d/bc -> null
  const node = await trie.get('c/cc/bd/d/bc')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, null)
  t.end()
})
