const test = require('tape')
const Trie = require('../../trie')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.symlink('/bcb', 'b')
  await trie.put('cb', 'pmorfzcyhz')
  // await trie.put('bcd', 'sxybizievv')
  // await trie.put('dddd', 'xfbnezbtdn')
  // await trie.put('bcbc', 'fdiykndrwz')

  // Should return cb -> pmorfzcyhz
  // Actually returns null -> null
  const node = await trie.get('cb')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, 'pmorfzcyhz')
  t.end()
})
