const test = require('tape')              
const Trie = require('../../trie')    
             
test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.symlink('/b/b/bd', 'b')
  await trie.put('b/dbd/bc', 'jcreshwggd')
  await trie.symlink('c/..', 'b/b')
                                                                                
  // Should return b/dbd/bc -> jcreshwggd
  // Actually returns null -> null
  const node = await trie.get('b/dbd/bc')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, 'jcreshwggd')
  t.end()
})
