const test = require('tape')
const Trie = require('../../trie')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.symlink('/dc', 'b')
  await trie.put('dc', 'kfvwjytckg')
  await trie.symlink('/b', 'b/bdc/bbb')

  // Should return null -> null
  // Actually returns dc/bdc/bbb -> kfvwjytckg
  const node = await trie.get('dc/bdc/bbb')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, null)              
  t.end()                           
}) 
