const test = require('tape')
const Trie = require('../../trie')

test('failing autogenerated test case', async t => {
  const trie = new Trie()
  
  await trie.put('c/dd/bc/bd/d', 'mdddejbrfl')
  await trie.put('b/b/c', 'ftjubvpifh')
  await trie.rename('b/cb/c/c/b', 'b/bb/bb/b/cd')
  await trie.symlink('db/cd/c', 'c/b/b/d')
  await trie.rename('d/dc/b/db/c', 'c')
  
  // Should return c/dd/bc/bd/d -> mdddejbrfl
  // Actually returns null -> null
  const node = await trie.get('c/dd/bc/bd/d')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, 'mdddejbrfl')
  t.end() 
})
