const test = require('tape')
const Trie = require('../../trie')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.symlink('/b', 'd')
  await trie.symlink('/d/bc', 'b')
  await trie.put('b/dd/b/b/b', 'qxigzkopsd')
  await trie.put('b/d/b', 'hjjniilbpo')

  // Should return null -> null
  // Actually returns b/d/b -> hjjniilbpo
  const node = await trie.get('b/d/b')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, null)
  t.end()
})
