const test = require('tape')
const Trie = require('../../trie')

test('failing autogenerated test case', async t => {
  const trie = new Trie()

  await trie.rename('b', 'd/b')
  await trie.put('c/c', 'fpixdgmvxz')
  await trie.rename('b/b/db/c/b', 'db')

  // Should return null -> null
  // Actually returns d/d/b -> d/b
  const node = await trie.get('d/d/b')
  const value = (node && node.value) ? node.value.value : null
  t.same(value, null)
  t.end()
})
